set_property PACKAGE_PIN H5 [get_ports {gpio_rtl_leds_tri_io[0]}]
set_property PACKAGE_PIN J5 [get_ports {gpio_rtl_leds_tri_io[1]}]
set_property PACKAGE_PIN T10 [get_ports {gpio_rtl_leds_tri_io[3]}]
set_property PACKAGE_PIN T9 [get_ports {gpio_rtl_leds_tri_io[2]}]
set_property PACKAGE_PIN D9 [get_ports {gpio_rtl_pause_btn_tri_io[0]}]
set_property PACKAGE_PIN A8 [get_ports {gpio_rtl_dir_sw_tri_io[0]}]
set_property PACKAGE_PIN C2 [get_ports reset_rtl_0]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_dir_sw_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_leds_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_leds_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_leds_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_leds_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_pause_btn_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports reset_rtl_0]

set_property IOSTANDARD LVCMOS33 [get_ports clk_100MHz]
set_property PACKAGE_PIN E3 [get_ports clk_100MHz]
